script:
  - ./autogen.sh
  - make
  - make check

env:
  - PYTHON=python2.7
  - PYTHON=python3.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq automake autoconf libglib2.0-dev libtool python-gi-dev libbluetooth-dev intltool python-dev python3-dev cython python-dbus python3-dbus dh-autoreconf
